export default {
  BASIC_ACTION: "BASIC_ACTION",
  GET_HEADER: "GET_HEADER",
  GOT_STUFF: "GOT_STUFF",
  GOT_NO_STUFF: "GOT_NO_STUFF",
  GET_VIDEOS: "GET_VIDEOS",
  GOT_VIDEOS: "GOT_VIDEOS",
  GET_QUOTES: "GET_QUOTES",
  GOT_QUOTES: "GOT_QUOTES"
};
